@startuml
hide footbox

participant "Line App" as lineApp
participant "Line Web" as lineWebView
participant "Line Open API" as lineApi

participant "3rd Web view" as partnerWebView
participant "JS SDK" as jsSdk

lineApp -> lineApp : open liff app with
note left
    http://liff.line.me/{liffId}
end note

lineApp -> lineApi : generate access_token for {liffId}
activate lineApi
note right
<b>(Oauth2 Implicit Grant Type)</b>
end note
lineApi -> lineApi : check permission allow
group first time usage
lineApi -> lineWebView : redirect to permission screen

lineWebView --> lineApi : grant permission
end

lineApi -> lineApi : create access_token
lineApi -> lineApp : return access_token
deactivate lineApi

note right
- access_token
- context_token
- feature_token
- id_token
- client_id
- mst_challenge
- redirect_url
end note

lineApp -> partnerWebView : open internal browser
note right
using url fragment (hashtag)
https://{redirect_url}#access_token={access_token}&client_id={client_id}...
end note

partnerWebView -> jsSdk : execute javascript
jsSdk -> jsSdk : initialize context

!include liff_js_sdk.puml!store_token
@enduml